# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-15 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='definition',
            field=models.TextField(null=True),
        ),
    ]
