# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_account', '0002_auto_20160915_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='term',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
