# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-02 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_account', '0003_auto_20160920_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_helps', to='tutor_account.UserProfile'),
        ),
    ]
