# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_account', '0008_helpdate_helptime_record_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='help',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered_timetable', to='tutor_account.Help'),
        ),
    ]
