# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_system', '0004_help_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='help',
            name='student',
        ),
        migrations.AddField(
            model_name='helpreceived',
            name='help',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='help_system.Help'),
        ),
        migrations.AddField(
            model_name='helpreceived',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_helps', to='help_system.UserProfile'),
        ),
    ]
