# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_system', '0005_auto_20161004_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='help',
            name='date',
        ),
        migrations.AddField(
            model_name='help',
            name='date',
            field=models.ManyToManyField(related_name='helps', to='help_system.Date'),
        ),
    ]
