# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_system', '0009_table_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='help',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='help_system.Help'),
        ),
    ]
