# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_system', '0010_record_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='help',
        ),
        migrations.RemoveField(
            model_name='table',
            name='record',
        ),
        migrations.AlterModelOptions(
            name='helptime',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['date']},
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
